name: Feature Request
description: Suggest a new feature or improvement
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement! Help us understand what you'd like to see.

  - type: textarea
    id: feature_description
    attributes:
      label: Feature Description
      description: |
        What feature would you like to see added or improved?
        Be clear and concise about what you want.
      placeholder: |
        I would like to be able to...

        This would allow users to...
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use Case / Problem It Solves
      description: |
        Why do you need this feature?
        What problem does it solve?
        How would it improve your experience?
      placeholder: |
        Currently, I have to manually...
        This feature would help because...
        My use case is...
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed Solution
      description: |
        How would you like this feature to work?
        Describe the ideal behavior and user experience.
      placeholder: |
        The feature should:
        1. Allow users to...
        2. When X happens, Y should...
        3. Configuration would look like...
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: |
        Are there other ways to solve this problem?
        Why is your proposed solution better?
      placeholder: |
        Alternative 1: ...
        Why this isn't ideal: ...

        Alternative 2: ...
        Why this isn't ideal: ...
    validations:
      required: false

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What area does this feature affect?
      options:
        - "LLM Integration (OpenAI, Ollama, etc.)"
        - "Memory System"
        - "Vector DB / Semantic Search"
        - "Tool Calling / Automations"
        - "Context Management"
        - "Configuration / UI"
        - "Performance / Optimization"
        - "Documentation"
        - "Other"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - "Low - Nice to have"
        - "Medium - Would be helpful"
        - "High - Important for my use case"
        - "Critical - Blocking me from using this component"
    validations:
      required: false

  - type: textarea
    id: additional_context
    attributes:
      label: Additional Context
      description: Any other information or examples?
      placeholder: |
        - Examples of similar features in other tools
        - Relevant documentation links
        - Screenshots or diagrams

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: "I've checked existing issues and discussions for similar requests"
          required: true
        - label: "This feature aligns with Home Agent's goals"
          required: false
        - label: "I would be willing to help implement this"
          required: false
